version: '3'

services:

  keycloak:
    container_name: keycloak_postgres
    image: quay.io/keycloak/keycloak:21.1
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
      - KC_HOSTNAME=localhost
    depends_on:
      db:
        condition: service_healthy
    networks:
      - keycloak_postgres_network

  db:
    container_name: postgres_12
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    networks:
      - keycloak_postgres_network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=keycloak
      - PG_DATA=/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  keycloak_postgres_network:
    name: keycloak_postgres_network
    driver: bridge

volumes:
  dbdata:
    driver: local